### ISSUE TITLE
Input validation for Insert page

### ISSUE THREAD

**Issue by tpetricek** [tpetricek/FsSnip.Website#12]
Currently, the input page has no input validation. Here is a list of things we need to add
### Server-side validation

Check that nothing is missing for public snippets and that basic things are provided for non-hidden snippet
### Client-side validation

Can we check the same rules in the Bootstrap form?
### Background formatting

It would be nice to format the snippet in the background and send it back as a preview.

**Comment by tpetricek** [comment]
Type checking of F# code is now done. So, we just need to validate the rest of the inputs :)

**Comment by patrick-mackay** [comment]
Tomas, I added validation using jquery validation plug in.

It works when updating and inserting.

I decided to keep the code validation as is working right now, and not include it in a "remote" validation, because that implied that we had to change the output of the api and I'm not sure it's worthwhile.

Please consider that english is not my native language, so please check the wording and change it if you think there are better ways to say the same.

Off topic: I'm still not sure that I'm using the git client correctly. Let me know if I'm doing something that shouldn't be doing.

**Comment by patrick-mackay** [comment]
Tomas, regarding the background formatting, I was thinking two options, but both have cons.

We could create another method in insert.fs near checkSnippet (for instance formatSnippet), but that mean that we'll have to call 2 methods, one to validate and the other to format the snippet. Even, the format method must validate the snippet again.

We could "enhance" checkSnippet, to return either a group of errors (same behavior that have now) o in case of no error, return the formatted snippet.

I prefer the second, but I don't like to mix responsibilities.

After writting all this, I realized that we could change the name of checkSnippet to formatSnippet and do both tasks, and we'll not cheat that much.

Maybe I'm over complicating this stuff, but since this is shared and I'm not used to this, I prefer to ask.

**Comment by tpetricek** [comment]
I think we already have all of these :) I added the background type checking some time ago (as per the above comment)

**Comment by patrick-mackay** [comment]
Yes, I re-read my comment again and I'm not sure what was I was trying to ask... At that time it surely seemed relevant...

Date: Tue, 12 Jan 2016 11:34:56 -0800
