### ISSUE TITLE
Report nice error when snippet is not found

### ISSUE THREAD

**Issue by tpetricek** [tpetricek/FsSnip.Website#5]
In `showSnippet` and `showRawSnippet`, we should check that the snippet exists. If it does not exist, we should report a nice error.

**Comment by froberg** [comment]
Hi @tpetricek , 
My first commit and I am quite new to F# and Suave [c9f57b7](https://github.com/froberg/FsSnip.Website/commit/c9f57b7f34360b855af6c5cf492970a095aea228)
Not sure if its usable but I created a new page for messages and returning with appropriate string as message. I left the **raw** function untouched assuming that a 404 can be helpful?

I choose to use `try .. with` because I get a **FileNotFound** when trying to access an invalid snippet. 
One annoying thing I have is that I don't know what to do with the exception I [catch](https://github.com/froberg/FsSnip.Website/blob/c9f57b7f34360b855af6c5cf492970a095aea228/code/common/data.fs#L68). 
Maybe an idea is to return **Success** or **Fail** discriminated unions instead of failing from the two storage files?

Thanks
// Chris

**Comment by tpetricek** [comment]
Hi Chris, thanks for looking into this :-). I love the fact that people new to F# can contribute to this project!

I think adding a separate error page is a great way of doing this! 

As for handling the errors, I think having a DU with `Success` (containing the result) or `Fail` (with the error message) would be really a good fit here. We could actually change `Storage.readFile` so that it returns a value of this DU (and so the result of `loadSnippetInternal` would be this DU value with error message saying that the ID is invalid (when we cannot find it in `publicSnippets`) or with a message saying that the version is wrong (when the file does not exist).

There is a [library called Chessie](http://fsprojects.github.io/Chessie/) that defines a DU like this, so we could use the library. The library does a lot more, but I wouldn't go too crazy with it and use just the basics (roughly the first 150 lines [from the source code](https://github.com/fsprojects/Chessie/blob/master/src/Chessie/ErrorHandling.fs)).

You could use the `Trial.failIfNone` function to turn the F# option we get from `Seq.tryFind` into a Chessie DU and then `Trial.bind` to do the next operation if the first one has not failed.

Let me know if this makes sense! 

(I'll also add some comments to your commit)

**Comment by tpetricek** [comment]
I sent you a PR that adds reference to Chessie: https://github.com/froberg/FsSnip.Website/pull/1

**Comment by froberg** [comment]
Thanks for the feedback. I added title to the message model as well as a helper function to change the status code to 404. (b98ff12) with help from the Suave's gitter. :)

As for the DU on reading files I tried Chessie but could not figure out how to use it properly and what I came up with didn't make any sense. I ended up using **option** instead. Not sure if that is good enough?
(042169b)

I went a bit mental with git and rebasing but last 3 commits that counts.

**Comment by tpetricek** [comment]
I created a PR with your changes: https://github.com/tpetricek/FsSnip.Website/pull/51 - I didn't see your changes in the list of pull requests, so I didn't realize it was waiting there :).

I just merged it and updated it to match the other changes, thanks again for looking into this!
