### ISSUE TITLE
The "like this" link in snippet details is not implemented

### ISSUE THREAD

**Issue by tpetricek** [tpetricek/FsSnip.Website#8]
This should increment the number of likes for the snippet and save the `index.json` file. This should be done with a bit of JavaScript without refreshing the whole page.

**Comment by abjrcode** [comment]
I will take this one too.

A few questions:
- Does Suave support server side events ?
- Should I increment the number on the client-side via JavaScript or get the new number of likes from the server ? I am asking about this because what if the user presses like and suddenly he sees that the number of likes increased by 4 or any other random number because other people liked the snippet at the same time ?
- What about the user clicking the like button more than one time, a cookie to solve this ?!

**Comment by tpetricek** [comment]
Solved by #31
