### ISSUE TITLE
Tooltip implementation

### ISSUE THREAD

**Issue by ShalokShalom** [tpetricek/FsSnip.Website#86]
Hi there - I consider implementing the tooltip engine into Gitea - is this an own implementation?

How do you recommend to implement the whole stuff, so including syntax highlighting?

**Comment by tpetricek** [comment]
The F# Snippets web site is using (fairly directly) the F# Formatting library for colorization and tool tips. The documentation shows this: https://fsprojects.github.io/FSharp.Formatting/codeformat.html

In F# Snippets, we use it here: https://github.com/fssnippets/fssnip-website/blob/master/code/common/parser.fs#L69 

The main tricky thing that fssnip.net does in addition to using the simple F# Formatting call is that we also download NuGet packages and reference the extracted files (so that you get tooltips for 3rd party libraries). That would be an awesome feature to have for Gitea, but it's a bit more tricky, I suppose!
